apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-workshop-example-config
data:
  config.yaml: |
    crash: false
    slow: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-workshop-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - name: app
          image: dpejcev/testkube-triggers-example:1.0.12
          ports:
            - containerPort: 8080
          env:
            - name: CONFIG_PATH
              value: "/app/config.yaml"
          volumeMounts:
            - mountPath: "/app"
              name: app-config
      volumes:
        - name: app-config
          configMap:
            name: k8s-workshop-example-config
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-workshop-example
spec:
  selector:
    app: example
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP