apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-workshop-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - name: app
          image: dpejcev/testkube-triggers-example:1.0.12
          ports:
            - containerPort: 8080
          env:
            - name: CONFIG_PATH
              value: "/app/config.yaml"
          volumeMounts:
            - mountPath: "/app"
              name: app-config
      volumes:
        - name: app-config
          configMap:
            name: k8s-workshop-example-config